---
driver:
  name: vagrant
  gui: true
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  require_chef_omnibus: true

verifier:
  name: inspec

platforms:
  - name: OctopusServer
    transport:
      name: winrm
      elevated: true

suites:
  - name: default
    run_list:
      - recipe[octochef::default]
    attributes:
