name 'octochef'
maintainer 'Shaw Inneses'
maintainer_email 'shaw@immortal.net.au'
license 'all_rights'
description 'Installs/Configures OctoChef Demo'
long_description 'Installs/Configures OctoChef Demo'

version '0.1.0'

depends 'windows'
depends 'ms_dotnet'
depends 'windows_firewall'
depends 'iis'
depends 'patch'
depends 'powershell'
